language: c++

dist: bionic
sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
    - bazel
    - build-essential
    - gcc-9
    - g++-9
    - doxygen
    - texlive-font-utils

install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90

before_script:
- cd src

script:
- ./make.sh all
